name: Work with Github actions
on: ["push"]

jobs: 
  task1:
    runs-on: ubuntu-latest
    needs: []
    steps: 
      - name: List file directory
        run: ls -lh
        
      - name: Make some changes
        run: mkdir tmp_dir && cd tmp_dir

  task2:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        list: ["1", "2", "3"]
    
    steps:
      - name: work with matrix
        run: echo ${{matrix.list}} 